import "./globals.css";
import { TaskProvider } from "../context/TaskContext";
import { Navbar } from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*este contiene todas la pagina y añadimos el taskprovider como parte del context para que todos los childerns tengan acceso*/}

      <body>
        <TaskProvider>
          <Navbar />
          {children}
        </TaskProvider>
      </body>
    </html>
  );
}
